import {populateDependencyGraph} from 'ts-loader/dist/utils';

export enum Platform {
    avito = 'avito',
}

export enum City {
    spb = 'spb',
    msk = 'msk',
}

export enum Transmission {
    auto = 'auto',
    akpp = 'akpp',
    robot = 'robot',
    vary = 'vary',
    mechanic = 'mechanic',
}

export enum Condition {
    hit = 'hit',
    notHit = 'notHit',
}

export enum Seller {
    dealer = 'dealer',
    private = 'private',
}

export enum Drive {
    front = 'front',
    back = 'back',
    full = 'full',
}

export enum Wheel {
    right = 'right',
    left = 'left',
}

export enum EngineType {
    disel = 'disel',
    petrol = 'petrol',
    hybrid = 'hybrid',
    electric = 'electric',
}

export enum BackType {
    sedan = 'sedan',
    offroadThreeDoors = 'offroadThreeDoors',
    offroadFiveDoors = 'offroadFiveDoors',
    universal = 'universal',
    hatchbackThreeDoors = 'hatchbackThreeDoors',
    hatchbackFiveDoors = 'hatchbcakFiveDoors',
    coupe = 'coupe',
    minivan = 'minivan',
    minibus = 'minibus',
    liftback = 'liftback',
    pickup = 'pickup',
    van = 'van',
    cabrio = 'cabrio'
}

export enum Brand {
    AC = 'AC',
    AITO = 'AITO',
    AMGeneral = 'AMGeneral',
    AMC = 'AMC',
    Acura = 'Acura',
    Adler = 'Adler',
    AlfaRomeo = 'AlfaRomeo',
    Alpina = 'Alpina',
    Alpine = 'Alpine',
    Amico = 'Amico',
    Amphicar = 'Amphicar',
    Arcfox = 'Arcfox',
    Ariel = 'Ariel',
    Aro = 'Aro',
    Asia = 'Asia',
    AstonMartin = 'AstonMartin',
    Auburn = 'Auburn',
    Audi = 'Audi',
    Aurus = 'Aurus',
    Austin = 'Austin',
    AustinHealey = 'AustinHealey',
    Autobianchi = 'Autobianchi',
    Avatr = 'Avatr',
    BAIC = 'BAIC',
    BAW = 'BAW',
    BMW = 'BMW',
    BYD = 'BYD',
    Bajaj = 'Bajaj',
    BaltijasDzips = 'BaltijasDzips',
    Baojun = 'Baojun',
    Barkas = 'Barkas',
    Bentley = 'Bentley',
    Bertone = 'Bertone',
    Bilenkin = 'Bilenkin',
    BioAuto = 'BioAuto',
    Bitter = 'Bitter',
    Blaval = 'Blaval',
    Borgward = 'Borgward',
    Brilliance = 'Brilliance',
    Bristol = 'Bristol',
    Bufori = 'Bufori',
    Bugatti = ' Bugatti',
    Buick = 'Buick',
    Cadillac = 'Cadillac',
    Callaway = 'Callaway',
    Caterham = 'Caterham',
    ChangFeng = 'ChangFeng',
    Channgan = 'Changan',
    Changhe = 'Changhe',
    Chery = 'Chery',
    CheryExceed = 'CheryExceed',
    Chevrolet = 'Chevrolet',
    Chrysler = 'Chrysler',
    Citroen = 'Citroen',
    Cizeta = 'Cizeta',
    Coggiola = 'Coggiola',
    Cord = 'Cord',
    Cupra = 'Cupra',
    DKW = 'DKW',
    DS = 'DS',
    DWHower = 'DWHower',
    Dacia = 'Dacia',
    Dadi = 'Dadi',
    Deawoo = 'Deawoo',
    Daihatsu = 'Daihatsu',
    Daimler = 'Daimler',
    Datsun = 'Datsun',
    Dayun = 'Dayun',
    DeTomaso = 'DeTomaso',
    DeLorean = 'DeLorean',
    DeSoto = 'DeSoto',
    Delage = 'Delage',
    Denza = 'Denza',
    Derways = 'Derways',
    Dodge = 'Dodge',
    Dongfeng = 'Dongfeng',
    Doninvest = 'Doninvest',
    Donkervoort = 'Donkervoort',
    ECar = 'ECar',
    EXEED = 'EXEED',
    Eagle = 'Eagle',
    EagleCars = 'EagleCars',
    Evolute = 'Evolute',
    Excalibur = 'Excalibur',
    FAW = 'FAW',
    FIAT = 'FIAT',
    FSO = 'FSO',
    Farizon = 'Farizon',
    Ferrari = 'Ferrari',
    Fisker = 'Fisker',
    Ford = 'Ford',
    Forthing = 'Forthing',
    Foton = 'Foton',
    Fuqi = 'Fuqi',
    GAC = 'GAC',
    GMC = 'GMC',
    GP = 'GP',
    Geely = 'Geely',
    Genesis = 'Genesis',
    Geo = 'Geo',
    GoldenDragon = 'GoldenDragon',
    Gonow = 'Gonow',
    Gordon = 'Gordon',
    GrahamPaige = 'GrahamPaige',
    GreatWall = 'GreatWall',
    Groz = 'Groz',
    HSV = 'HSV',
    Hafei = 'Hafei',
    Haima = 'Haima',
    Hanomag = 'Hanomag',
    Hawtai = 'Hawtai',
    Heinkel = 'Heinkel',
    HiPhi = 'HiPhi',
    Hindustan = 'Hindustan',
    HispanoSuiza = 'HispanoSuiza',
    Hobbycar = 'Hobbycar',
    Honda = 'Honda',
    Horch = 'Horch',
    Huanghai = 'Huanghai',
    Hudson = 'Hudson',
    Hummer = 'Hummer',
    Hyundai = 'Hyundai',
    Imperial = 'Imperial',
    Infinity = 'Infinity',
    Innocenti = 'Innocenti',
    Incicta = 'Invicta',
    IranKhodro = 'IranKhodro',
    Isdera = 'Isdera',
    Isuzu = 'Isuzu',
    Iveco = 'Iveco',
    JAC = 'JAC',
    JMC = 'JMC',
    Jaecoo = 'Jaecoo',
    Jaguar = 'Jaguar',
    Jeep = 'Jeep',
    Jensen = 'Jensen',
    Jetour = 'Jetour',
    Jetta = 'Jetta',
    Jidu = 'Jidu',
    Jinbei = 'Jinbei',
    Jonway = 'Jonway',
    KTM = 'KTM',
    KYC = 'KYC',
    Kaiyi = 'Kaiyi',
    KangarooElectro = 'KangarooElectro',
    Khazar = 'Khazar',
    Kia = 'Kia',
    Koenigsegg = 'Koenigsegg',
    LDV = 'LDV',
    LIFAN = 'LIFAN',
    LTI = 'LTI',
    Lamborghini = 'Lamborghini',
    Lancia = 'Lancia',
    LandRover = 'LandRover',
    Landwind = 'Landwind',
    Leapmotor = 'Leapmotor',
    Lexus = 'Lexus',
    Leyland = 'Leyland',
    LiXiang = 'LiXiang',
    Lichi = 'Lichi',
    Ligier = 'Ligier',
    Lincoln = 'Lincoln',
    Livan = 'Livan',
    Lotus = 'Lotus',
    Lucid = 'Lucid',
    Luxgen = 'Luxgen',
    LynkCo = 'LynkCo',
    MAN = 'MAN',
    MG = 'MG',
    MINI = 'MINI',
    Mahindra = 'Mahindra',
    Maple = 'Maple',
    Marcos = 'Marcos',
    Marlin = 'Marlin',
    Marussia = 'Marussia',
    Maruti = 'Maruti',
    Maserati = 'Maserati',
    Maxus = 'Maxus',
    MAybach = 'Maybach',
    Mazda = 'Mazda',
    McLaren = 'McLaren',
    Mega = 'Mega',
    MercedesBenz = 'MercedesBenz',
    Mercury = 'Mercury',
    Messerschmitt = 'Messerschmitt',
    Metrocab = 'Metrocab',
    Microcar = 'Microcar',
    Minelli = 'Minelli',
    Mitsubishi = 'Mitsubishi',
    Mitsuoka = 'Mitsuoka',
    Morgan = 'Morgan',
    Morris = 'Morris',
    NIO = 'NIO',
    Nash = 'Nash',
    Neta = 'Neta',
    Nissan = 'Nissan',
    Noble = 'Noble',
    Nysa = 'Nysa',
    OMODA = 'OMODA',
    Oldsmobile = 'Oldsmobile',
    Opel = 'Opel',
    Ora = 'Ora',
    Osca = 'Osca',
    Oshan = 'Oshan',
    Overland = 'Overland',
    PGO = 'PGO',
    PUCH = 'PUCH',
    Packard = 'Packard',
    Pagani = 'Pagani',
    Panhard = 'Panhard',
    Panoz = 'Panoz',
    Peugeot = 'Peugeot',
    Piaggio = 'Piaggio',
    Plymouth = 'Plymouth',
    Polestar = 'Polestar',
    Pontiac = 'Pontiac',
    Porsche = 'Porsche',
    Premier = 'Premier',
    Proton = 'Proton',
    Puma = 'Puma',
    Qoros = 'Qoros',
    Qvale = 'Qvale',
    RAM = 'RAM',
    Ravon = 'Ravon',
    RaytonFissore = 'RaytonFissore',
    Reliant = 'Reliant',
    Renaissance = 'Renaissance',
    Renault = 'Renault',
    Rezvani = 'Rezvani',
    Rimac = 'Rimac',
    Rinspeed = 'Rinspeed',
    RisingAuto = 'RisingAuto',
    Rivian = 'Rivian',
    Rocar = 'Rocar',
    Roewe = 'Roewe',
    RollsRoyce = 'RollsRoyce',
    Ronart = 'Ronart',
    Rover = 'Rover',
    SEAT = 'SEAT',
    SMA = 'SMA',
    SOL = 'SOL',
    Saab = 'Saab',
    Saic = 'Saic',
    Saipa = 'Saipa',
    Saleen = 'Saleen',
    Santana = 'Santana',
    Saturn = 'Saturn',
    Scion = 'Scion',
    Seres = 'Seres',
    Shuanghuan = 'Shuanghuan',
    Simca = 'Simca',
    Skoda = 'Skoda',
    Skywell = 'Skywell',
    Smart = 'Smart',
    Sollers = 'Sollers',
    Soueast = 'Soueast',
    Spyker = 'Spyker',
    SsangYong = 'SsangYong',
    Steyr = 'Steyr',
    Studebaker = 'Studebaker',
    Subaru = 'Subaru',
    Suzuki = 'Suzuki',
    TVR = 'TVR',
    Talbot = 'Talbot',
    Tank = 'Tank',
    Tata = 'Tata',
    Tatra = 'Tatra',
    Tazzari = 'Tazzari',
    Tesla = 'Tesla',
    Think = 'Think',
    Tianma = 'Tianma',
    Tianye = 'Tianye',
    Toyota = 'Toyota',
    Trabant = 'Trabant',
    Tramontana = 'Tramontana',
    Triumph = 'Triumph',
    Trumpchi = 'Trumpchi',
    Ultima = 'Ultima',
    VGV = 'VGV',
    Vauxhall = 'Vauxhall',
    Vector = 'Vector',
    Venturi = 'Venturi',
    Volkswagen = 'Volkswagen',
    Volvo = 'Volvo',
    Vortex = 'Vortex',
    Voyah = 'Voyah',
    WMotors = 'WMotors',
    Wanderer = 'Wanderer',
    Wartburg = 'Wartburg',
    Weltmeister = 'Weltmeister',
    Westfield = 'Westfield',
    Wey = 'Wey',
    Wiesmann = 'Wiesmann',
    Willys = 'Willys',
    Wuling = 'Wuling',
    XPeng = 'XPeng',
    XinKai = 'XinKai',
    ZOTOYE = 'ZOTOYE',
    ZX = 'ZX',
    Zastava = 'Zastava',
    Zeekr = 'Zeekr',
    Zenos = 'Zenos',
    Zenovo = 'Zenovo',
    Zhiji = 'Zhiji',
    Zibar = 'Zibar',
    Zuk = 'Zuk',
    Avtokam = 'Avtokam',
    Apal = 'Apal',
    Bogdan = 'Bogdan',
    VAZLADA = 'VAZLADA',
    VIS = 'VIS',
    GAZ = 'GAZ',
    ErAZ = 'ErAZ',
    ZAZ = 'ZAZ',
    ZIL = 'ZIL',
    ZIS = 'ZIS',
    IZH = 'IZH',
    Kanonir = 'Kanonir',
    Kombat = 'Kombat',
    LuAZ = 'LuAZ',
    Moskvich = 'Moskvich',
    RAF = 'RAF',
    RussoBalt = 'RussoBalt',
    SMZ = 'SMZ',
    TagAZ = 'TagAZ',
    UAZ = 'UAZ'

}

export enum Color {
    white = 'white',
    gray = 'gray',
    silver = 'silver',
    black = 'black',
    brown = 'brown',
    gold = 'gold',
    beige = 'beige',
    red = 'red',
    vinous = 'vinous',
    orange = 'orange',
    yellow = 'yellow',
    green = 'green',
    lightBlue = 'lightBlue',
    blue = 'blue',
    violet = 'violet',
    purple = 'purple',
    pink = 'pink'
}

export interface SearchCarsData {
    platform: Platform;
    city: City;
    lastProcessedRecordTimestamp: string;
}
